variables:
  SLACK_AUTH_TOKEN: ""
  SLACK_CHANNEL: ""
  SLACK_MESSAGE: "This is a test"

slack_message:
  image: appropriate/curl:latest
  cache: { }
  script:
    - |-
      PAYLOAD=$(cat << JSON
      {
        "channel": "${SLACK_CHANNEL}",
        "text": "${SLACK_MESSAGE}",
      }
      JSON
      )
    - >
      curl -qsSf
      -X POST https://slack.com/api/chat.postMessage
      -H 'Content-type: application/json; charset=utf-8'
      -H "Authorization: Bearer ${SLACK_AUTH_TOKEN}"
      -d "${PAYLOAD}"
